### ISSUE TITLE
新增两个需求 能不能给弹幕一个速度参数

### ISSUE THREAD

**Issue by huanx9** [xhlove/GetDanMu#1]
能不能给弹幕一个速度参数  不知道怎么回事,2K看弹幕眼睛有点花。 

再给一个 -o  输出路径

感谢开发者 项目很牛！

**Comment by xhlove** [comment]
目前设定的是每个弹幕显示15s，是需要控制这个值吗？

**Comment by huanx9** [comment]
是的， 我的屏幕是60HZ的，我在怀疑是不是因为我屏幕刷新率不够所以导致看弹幕有点模糊，只要把弹幕停下来 还是很清晰的，所以我需要修改这个数值去降低弹幕的滚动速度..

**Comment by xhlove** [comment]
你可以手动修改这里的数值```show_time = 15```，越大移动速度就越慢。
https://github.com/xhlove/GetDanMu/blob/6ab886dd8fcacdf9a5ae27c389b7831cc8127abd/methods/assbase.py#L59
