### ISSUE TITLE
默认字体用迅雷播放器乱码

### ISSUE THREAD

**Issue by yclin20** [xhlove/GetDanMu#3]
下载的ass文件拖到迅雷播放器显示乱码，要另存为unicode编码才能解决，其他播放器没试过。
另外有没有可能实现精简弹幕的功能，有时候满屏都是弹幕。
最后感谢开发者，功能很强大。

**Comment by xbstory** [comment]
其他播放器加载字幕也会乱码吗？默认是微软雅黑，如果是windows平台应该不会有这个问题。

**Comment by yclin20** [comment]
迅雷播放器问题，PotPlayer正常
