### ISSUE TITLE
大佬, 是失效了嗎?

### ISSUE THREAD

**Issue by telanxrays** [xhlove/GetDanMu#6]
我試着下載騰訊視頻的彈幕, 但下載下來的全是0kb的ass文件, 但有提示下載進度什麽的, 就是文件沒內容. 怎麽回事? 是失效了嗎? 還是我的操作方法不對? 求告知, 非常感謝你的工作.

**Comment by xbstory** [comment]
使用如下命令测试，未复现你说的情况

```bash
python GetDanMu.py -s qq -vid y0036wp0o3u
```

![image](https://user-images.githubusercontent.com/48152166/116891893-d0cf8c00-ac61-11eb-9c72-1062ef551c52.png)


如果你在线观看无法加载出弹幕，有可能是地区的ip限制所致。

**Comment by telanxrays** [comment]
> 使用如下命令测试，未复现你说的情况
> 
> ```shell
> python GetDanMu.py -s qq -vid y0036wp0o3u
> ```
> 
> ![image](https://user-images.githubusercontent.com/48152166/116891893-d0cf8c00-ac61-11eb-9c72-1062ef551c52.png)
> 
> 如果你在线观看无法加载出弹幕，有可能是地区的ip限制所致。

多謝回復, 我再試試, 我是沒有登陸的, 直接輸入視頻的鏈接地址下的, 得到的是0kb的ass, 我試試你說的方法. 另外大佬你的VSCODE的粗體字體看起來好性感, 可否告知是什麽字體. 感謝😃😃

**Comment by telanxrays** [comment]
對了, 忘說了, 我是用的那個最終版本的1.6.2的exe弄的, 和py腳本用法有區別嗎?

**Comment by telanxrays** [comment]
![2021-05-04_001907](https://user-images.githubusercontent.com/54123851/116903058-7ee13300-ac6e-11eb-99c9-e4b9a7584f9e.png)
還是不行, 沒搞懂為什麽, 用py腳本和exe都試過, 用的你給的vid參數輸入視頻的vid也是0kb的ass, 這是下載完成後的信息, 似乎有錯誤, 說不能打開資源, 具體什麽資源不知道... 上面寫的字體什麽的, 不會是因為字體的關係吧? 我用的簡體系統但系統字體改成了繁體, 這有關係嗎? 另外cmd也用管理員試過, 路徑也是純英文路徑, 還是一樣結果...

**Comment by telanxrays** [comment]
![2021-05-04_002437](https://user-images.githubusercontent.com/54123851/116903554-25c5cf00-ac6f-11eb-88ab-c307f755f529.png)
這是用程序然後用相同參數下載的結果提示, 有點差異, 但結果相同, 創建文件失敗, 0容量.

**Comment by xbstory** [comment]
vscode字体是 Consolas

错误应该是系统没有微软雅黑（msyh.ttc）字体文件，你可以修改config.json，比如繁体的微軟雅黑 C:/Windows/Fonts 下对应的文件名

**Comment by telanxrays** [comment]
> vscode字体是 Consolas
> 
> 错误应该是系统没有微软雅黑（msyh.ttc）字体文件，你可以修改config.json，比如繁体的微軟雅黑 C:/Windows/Fonts 下对应的文件名

大佬! GET到了GET到了! 感謝指點! 我把config.json里的字體名稱和對應的文件名改成我系統正在用的, 然後ass.py裏面的font_style_name = 這一行後面的雅黑也改成config裏面的字體名, 然後就get到了! 果然是創建時的字體讀取出的問題! 再次感謝你提供的信息!!! 辛苦了!
